apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "default-rules.fullname" . }}
  labels:
    app: {{ include "default-rules.fullname" . }}

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app: {{ include "default-rules.fullname" . }}
  name: {{ include "default-rules.fullname" . }}
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "default-rules.fullname" . }}-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "default-rules.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "default-rules.fullname" . }}
  namespace: {{ .Release.Namespace }}

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "default-rules.fullname" . }}
rules:
- apiGroups:
  - '*'
  resources:
  - namespaces
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - update
  - watch
- apiGroups:
  - ""
  - events.k8s.io
  resources:
  - events
  verbs:
  - create
  - patch
  - update

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "default-rules.fullname" . }}-clusterbinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "default-rules.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "default-rules.fullname" . }}
  namespace: {{ .Release.Namespace }}